using System.Runtime.Serialization;

namespace Idfy.Addons.Entities.Organization
{
    public enum OrganizationInformationModelOrganizationType
    {
        [EnumMember(Value = "ADMINISTRATIVE_ENTITY_PUBLIC_SECTOR")]
        ADMINISTRATIVEENTITYPUBLICSECTOR,

        [EnumMember(Value = "OTHER_BODY_CORPORATE")]
        OTHERBODYCORPORATE,

        [EnumMember(Value = "GENERAL_PARTNERSHIP")]
        GENERALPARTNERSHIP,

        [EnumMember(Value = "LIMITED_COMPANY")]
        LIMITEDCOMPANY,

        [EnumMember(Value = "PUBLIC_LIMITED_COMPANY")]
        PUBLICLIMITEDCOMPANY,

        [EnumMember(Value = "COMPANY_WITH_LIMITED_LIABILITY")]
        COMPANYWITHLIMITEDLIABILITY,

        [EnumMember(Value = "HOUSE_BUILDING_COOPERATIVE")]
        HOUSEBUILDINGCOOPERATIVE,

        [EnumMember(Value = "OTHER_ESTATES")] OTHERESTATES,

        [EnumMember(Value = "HOUSING_COOPERATIVE")]
        HOUSINGCOOPERATIVE,

        [EnumMember(Value = "GENERAL_PARTNERSHIP_WITH_SHARED_LIABILITY")]
        GENERALPARTNERSHIPWITHSHAREDLIABILITY,

        [EnumMember(Value = "SOLE_PROPRIETORSHIP")]
        SOLEPROPRIETORSHIP,

        [EnumMember(Value = "EUROPEAN_COOPERATIVE_SOCIETY")]
        EUROPEANCOOPERATIVESOCIETY,

        [EnumMember(Value = "EUROPEAN_ECONOMIC_ENTERPRISE_GROUP")]
        EUROPEANECONOMICENTERPRISEGROUP,

        [EnumMember(Value = "CONDOMINIUM_FLAT_OWNER")]
        CONDOMINIUMFLATOWNER,

        [EnumMember(Value = "COUNTY_MUNICIPAL_BUSINESS_ENTERPRISE")]
        COUNTYMUNICIPALBUSINESSENTERPRISE,

        [EnumMember(Value = "ASSOCIATION_CLUB_ORGANIZATION")]
        ASSOCIATIONCLUBORGANIZATION,

        [EnumMember(Value = "COUNTY_MUNICIPALITY")]
        COUNTYMUNICIPALITY,

        [EnumMember(Value = "MUTUAL_INSURANCE_COMPANY")]
        MUTUALINSURANCECOMPANY,

        [EnumMember(Value = "HEALTH_AUTHORITIES_AND_HEALTH_TRUSTS")]
        HEALTHAUTHORITIESANDHEALTHTRUSTS,

        [EnumMember(Value = "OTHER_NONBODY_CORPORATE")]
        OTHERNONBODYCORPORATE,

        [EnumMember(Value = "INTERMUNICIPAL_COMPANY")]
        INTERMUNICIPALCOMPANY,

        [EnumMember(Value = "BANKRUPT_ESTATE")]
        BANKRUPTESTATE,

        [EnumMember(Value = "MUNICIPAL_BUSINESS_ENTERPRISE")]
        MUNICIPALBUSINESSENTERPRISE,

        [EnumMember(Value = "THE_CHURCH_OF_NORWAY")]
        THECHURCHOFNORWAY,

        [EnumMember(Value = "MUNICIPALITY")] MUNICIPALITY,

        [EnumMember(Value = "LIMITED_PARTNERSHIP")]
        LIMITEDPARTNERSHIP,

        [EnumMember(Value = "JOINT_OFFICE")] JOINTOFFICE,

        [EnumMember(Value = "NORWEGIAN_REGISTERED_FOREIGN_BUSINESS")]
        NORWEGIANREGISTEREDFOREIGNBUSINESS,

        [EnumMember(Value = "SPECIALLY_SECTIONED_UNIT")]
        SPECIALLYSECTIONEDUNIT,

        [EnumMember(Value = "ORGANIZATIONAL_SECTION")]
        ORGANIZATIONALSECTION,

        [EnumMember(Value = "OTHER_INDIVIDUALS_REGISTERED_IN_AFFILIATED_REGISTER")]
        OTHERINDIVIDUALSREGISTEREDINAFFILIATEDREGISTER,

        [EnumMember(Value = "PENSION_FUND")] PENSIONFUND,

        [EnumMember(Value = "JOINTLY_OWNED_SHIPPING_COMPANY")]
        JOINTLYOWNEDSHIPPINGCOMPANY,

        [EnumMember(Value = "REGIONAL_HEALTH_AUTHORITIES_AND_HEALTH_TRUSTS")]
        REGIONALHEALTHAUTHORITIESANDHEALTHTRUSTS,

        [EnumMember(Value = "COOPERATIVE")] COOPERATIVE,

        [EnumMember(Value = "JOINT_OWNERSHIP_ACCORDING_TO_THE_LAW_OF_PROPERTY")]
        JOINTOWNERSHIPACCORDINGTOTHELAWOFPROPERTY,

        [EnumMember(Value = "EUROPEAN_COMPANY")]
        EUROPEANCOMPANY,

        [EnumMember(Value = "PUBLIC_CORPORATION")]
        PUBLICCORPORATION,

        [EnumMember(Value = "SAVINGS_BANK")] SAVINGSBANK,

        [EnumMember(Value = "STATE")] STATE,

        [EnumMember(Value = "FOUNDATION")] FOUNDATION
    }
}